# Generated by Django 4.2.7 on 2023-12-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementsInfometion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationFormRadioButton', models.TextField(choices=[('0', 'エスコート'), ('1', 'MySTYLE(UAH含む)'), ('2', '航空券 '), ('3', 'ホテル')], verbose_name='登録形態')),
                ('outputDestinationJtbChackBox', models.BooleanField(verbose_name='出力先_JTB')),
                ('outputDestinationTravelChackBox', models.BooleanField(verbose_name='出力先_トラベルコ')),
                ('outputDestinationPamphletChackBox', models.BooleanField(verbose_name='出力先_パンフレット')),
                ('departurePoint', models.CharField(max_length=255, verbose_name='出発地')),
                ('adultNum', models.IntegerField(blank=True, default=0, null=True, verbose_name='大人人数')),
                ('departureDateSettingRadio', models.TextField(choices=[('0', '絶対設定'), ('1', '相対設定1'), ('2', '相対設定2')], verbose_name='出発日設定時間')),
                ('absoluteSettingStartDate', models.DateTimeField(blank=True, null=True, verbose_name='絶対設定_開始日付')),
                ('absoluteSettingEndDate', models.DateTimeField(blank=True, null=True, verbose_name='絶対設定_終了日付')),
                ('relativeSettings1StartList', models.CharField(blank=True, max_length=255, null=True, verbose_name='相対設定1_開始リスト')),
                ('relativeSettings1EndList', models.CharField(blank=True, max_length=255, null=True, verbose_name='相対設定1_終了リスト')),
                ('relativeSettings2StartDayTxt', models.CharField(blank=True, max_length=255, null=True, verbose_name='相対設定2_開始日')),
                ('relativeSettings2EndDayTxt', models.CharField(blank=True, max_length=255, null=True, verbose_name='相対設定2_終了日')),
                ('rootPackageId', models.CharField(blank=True, max_length=255, null=True, verbose_name='ルートパッケージID')),
                ('firstCity', models.CharField(blank=True, max_length=255, null=True, verbose_name='1都市目')),
                ('firstCityDepartureDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='1都市目_現地出発日')),
                ('firstCityHotelTariffCode1', models.CharField(blank=True, max_length=255, null=True, verbose_name='1都市目_ホテルタリフコード1')),
                ('firstCityHotelTariffCode2', models.CharField(blank=True, max_length=255, null=True, verbose_name='1都市目_ホテルタリフコード2')),
                ('firstCityLopCompanyCode', models.CharField(blank=True, max_length=255, null=True, verbose_name='1都市目_LOP会社コード')),
                ('firstCityPlanId', models.CharField(blank=True, max_length=255, null=True, verbose_name='1都市目_プランID')),
                ('secondtCity', models.CharField(blank=True, max_length=255, null=True, verbose_name='2都市目')),
                ('secondtCityDepartureDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='2都市目_現地出発日')),
                ('secondtCityHotelTariffCode1', models.CharField(blank=True, max_length=255, null=True, verbose_name='2都市目_ホテルタリフコード1')),
                ('secondtCityHotelTariffCode2', models.CharField(blank=True, max_length=255, null=True, verbose_name='2都市目_ホテルタリフコード2')),
                ('thirdCity', models.CharField(blank=True, max_length=255, null=True, verbose_name='3都市目')),
                ('thirdCityDepartureDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='3都市目_現地出発日')),
                ('thirdCityHotelTariffCode1', models.CharField(blank=True, max_length=255, null=True, verbose_name='3都市目_ホテルタリフコード1')),
                ('thirdCityHotelTariffCode2', models.CharField(blank=True, max_length=255, null=True, verbose_name='3都市目_ホテルタリフコード2')),
                ('airlinesSelectTxt', models.CharField(blank=True, max_length=255, null=True, verbose_name='航空会社')),
                ('useDirectFlightChackBox', models.BooleanField(verbose_name='直行便指定')),
                ('cabinClassOutboundTripRadioButton', models.TextField(blank=True, choices=[('0', 'エコノミー'), ('1', 'プレミアムエコノミー'), ('2', 'ビジネス '), ('3', 'ファースト')], null=True, verbose_name='キャビンクラス（往路）')),
                ('cabinClassRoundTripRadioButton', models.TextField(blank=True, choices=[('0', 'エコノミー'), ('1', 'プレミアムエコノミー'), ('2', 'ビジネス '), ('3', 'ファースト')], null=True, verbose_name='キャビンクラス（複路）')),
                ('flightNumberOutboundTripTxt', models.CharField(blank=True, max_length=255, null=True, verbose_name='便名（往路）')),
                ('flightNumberRoundTripTxt', models.CharField(blank=True, max_length=255, null=True, verbose_name='便名（複路）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
