# Generated by Django 4.2.7 on 2023-12-01 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentId', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsInfometion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationFormRadioButton', models.CharField(max_length=255, verbose_name='')),
                ('outputDestinationJtbChackBox', models.BooleanField(max_length=255, verbose_name='')),
                ('outputDestinationTravelChackBox', models.BooleanField(max_length=255, verbose_name='')),
                ('outputDestinationPamphletChackBox', models.BooleanField(max_length=255, verbose_name='')),
                ('departurePoint', models.CharField(max_length=255, verbose_name='')),
                ('adultNum', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('departureDateSettingRadio', models.CharField(max_length=255, verbose_name='')),
                ('absoluteSettingStartDate', models.DateTimeField(blank=True, null=True, verbose_name='')),
                ('absoluteSettingEndDate', models.DateTimeField(blank=True, null=True, verbose_name='')),
                ('relativeSettings1StartList', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('relativeSettings1EndList', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('relativeSettings2StartDayTxt', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('relativeSettings2EndDayTxt', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('contentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.contentid')),
            ],
        ),
    ]
